DEBUG_LEVEL: "DEBUG"   # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

ESP_SENSOR:
  ESP_READER_HOST: "192.168.30.182"
  ESP_READER_PORT: 6053
  ESP_READER_ENCRYPTION_KEY: "004Nt8RGUB3CMOGb9vnY3sCblsx8vYbZSwrSwE2UbOE="
  ESP_READER_WINDOW_SECONDS: 0.5

INVERTER:
  SOLAR_EDGE_INVERTER_DEVICE: "/dev/ttyUSB0"
  SOLAR_EDGE_INVERTER_BAUD: 9600
  SOLAR_EDGE_INVERTER_TIMEOUT: 2

API:
  TOKEN: "YourSecretTokenHere"
